# Generated by Django 6.0.7 on 2026-08-04 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jingle',
            name='business_name',
        ),
    ]
