# Generated by Django 6.0.7 on 2026-08-04 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_remove_jingle_business_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jingle',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='jingle',
            name='prompt',
        ),
        migrations.RemoveField(
            model_name='jingle',
            name='script',
        ),
        migrations.CreateModel(
            name='JingleAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='jingles/')),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('jingle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio', to='studio.jingle')),
            ],
        ),
        migrations.CreateModel(
            name='JingleMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('jingle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='studio.jingle')),
            ],
        ),
    ]
